//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using SIUGJ.Helpers;

namespace WSMobileSIUGJ
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = Constants.NameWebServices, ConfigurationName="WSMobileSIUGJ.ApplicationServicesPortType")]
    public interface ApplicationServicesPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="autenticateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string autenticateUser(string urlAutentication, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="autenticateUser", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> autenticateUserAsync(string urlAutentication, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="usersTask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string usersTask(string stringTokenAccess, string token, string taskStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="usersTask", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> usersTaskAsync(string stringTokenAccess, string token, string taskStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="usersAudiences", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string usersAudiences(string stringTokenAccess, string token, string start, string end, string statusAudiences);
        
        [System.ServiceModel.OperationContractAttribute(Action="usersAudiences", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> usersAudiencesAsync(string stringTokenAccess, string token, string start, string end, string statusAudiences);
        
        [System.ServiceModel.OperationContractAttribute(Action="usersGetCourts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string usersGetCourts(string stringTokenAccess, string token, string state, string typeCout);
        
        [System.ServiceModel.OperationContractAttribute(Action="usersGetCourts", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> usersGetCourtsAsync(string stringTokenAccess, string token, string state, string typeCout);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ApplicationServicesPortTypeChannel : WSMobileSIUGJ.ApplicationServicesPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ApplicationServicesPortTypeClient : System.ServiceModel.ClientBase<WSMobileSIUGJ.ApplicationServicesPortType>, WSMobileSIUGJ.ApplicationServicesPortType
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ApplicationServicesPortTypeClient() : 
                base(ApplicationServicesPortTypeClient.GetDefaultBinding(), ApplicationServicesPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ApplicationServicesPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationServicesPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(ApplicationServicesPortTypeClient.GetBindingForEndpoint(endpointConfiguration), ApplicationServicesPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationServicesPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ApplicationServicesPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationServicesPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ApplicationServicesPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationServicesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string autenticateUser(string urlAutentication, string token)
        {
            return base.Channel.autenticateUser(urlAutentication, token);
        }
        
        public System.Threading.Tasks.Task<string> autenticateUserAsync(string urlAutentication, string token)
        {
            return base.Channel.autenticateUserAsync(urlAutentication, token);
        }
        
        public string usersTask(string stringTokenAccess, string token, string taskStatus)
        {
            return base.Channel.usersTask(stringTokenAccess, token, taskStatus);
        }
        
        public System.Threading.Tasks.Task<string> usersTaskAsync(string stringTokenAccess, string token, string taskStatus)
        {
            return base.Channel.usersTaskAsync(stringTokenAccess, token, taskStatus);
        }
        
        public string usersAudiences(string stringTokenAccess, string token, string start, string end, string statusAudiences)
        {
            return base.Channel.usersAudiences(stringTokenAccess, token, start, end, statusAudiences);
        }
        
        public System.Threading.Tasks.Task<string> usersAudiencesAsync(string stringTokenAccess, string token, string start, string end, string statusAudiences)
        {
            return base.Channel.usersAudiencesAsync(stringTokenAccess, token, start, end, statusAudiences);
        }
        
        public string usersGetCourts(string stringTokenAccess, string token, string state, string typeCout)
        {
            return base.Channel.usersGetCourts(stringTokenAccess, token, state, typeCout);
        }
        
        public System.Threading.Tasks.Task<string> usersGetCourtsAsync(string stringTokenAccess, string token, string state, string typeCout)
        {
            return base.Channel.usersGetCourtsAsync(stringTokenAccess, token, state, typeCout);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ApplicationServicesPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ApplicationServicesPort))
            {
                return new System.ServiceModel.EndpointAddress(Constants.UriWs);
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ApplicationServicesPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.ApplicationServicesPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ApplicationServicesPortTypeClient.GetEndpointAddress(EndpointConfiguration.ApplicationServicesPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ApplicationServicesPort,
        }
    }
}
